# Generated by Django 2.1.3 on 2018-12-08 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolStepParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='protocolparameter',
            name='protocol_step',
        ),
        migrations.RemoveField(
            model_name='biologicalreplicateprotocol',
            name='biological_replicate',
        ),
        migrations.AddField(
            model_name='protocolparameterdeviation',
            name='comment',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biologicalreplicate',
            name='biological_replicate_protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.BiologicalReplicateProtocol'),
        ),
        migrations.AlterField(
            model_name='biologicalreplicate',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='biologicalreplicatemetadata',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biologicalreplicatemetadata',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='biologicalreplicateprotocol',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='md5_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='institution',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='investigation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelinedeviation',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelineparameter',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelineparameter',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pipelinestep',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='protocolstep',
            name='method',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='protocolstep',
            name='step_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='value',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='ProtocolParameter',
        ),
        migrations.AddField(
            model_name='protocolstepparameter',
            name='biological_replicate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.ProtocolStep'),
        ),
    ]
