# Generated by Django 2.1.3 on 2018-12-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20181208_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolparameterdeviation',
            old_name='comment',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='protocolstep',
            name='description',
        ),
        migrations.AddField(
            model_name='protocolstepparameter',
            name='description',
            field=models.TextField(default='NA'),
            preserve_default=False,
        ),
    ]
