# Generated by Django 2.1.3 on 2019-01-17 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20181208_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='biologicalreplicate',
            name='investigation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.Investigation'),
            preserve_default=False,
        ),
    ]
