# Generated by Django 2.1.3 on 2019-01-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_biologicalreplicate_investigation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolstep',
            old_name='biological_replicate_protocol',
            new_name='biological_replicate_protocols',
        ),
        migrations.AddField(
            model_name='biologicalreplicateprotocol',
            name='citation',
            field=models.TextField(default='Citation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pipelineresult',
            name='replicates',
            field=models.ManyToManyField(to='db.BiologicalReplicate'),
        ),
    ]
