# Generated by Django 2.1.3 on 2019-01-22 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20190118_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolStepParameterDeviation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='protocolstepparameter',
            old_name='biological_replicate',
            new_name='protocol_step',
        ),
        migrations.AddField(
            model_name='biologicalreplicate',
            name='protocol_parameter_deviations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.ProtocolParameterDeviation'),
            preserve_default=False,
        ),
    ]
