# Generated by Django 2.1.3 on 2019-01-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20190122_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biologicalreplicate',
            name='protocol_parameter_deviations',
        ),
        migrations.AddField(
            model_name='protocolstepparameterdeviation',
            name='biological_replicate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.BiologicalReplicate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolstepparameterdeviation',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='protocolstepparameterdeviation',
            name='new_value',
            field=models.CharField(default='NEW', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protocolstepparameterdeviation',
            name='protocol_step_parameter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='db.ProtocolStepParameter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biologicalreplicate',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample', to='db.Sample'),
        ),
        migrations.AlterField(
            model_name='protocolstepparameter',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
