# Generated by Django 2.1.3 on 2019-01-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0007_auto_20190123_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='protocolstep',
            old_name='step_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='protocolstep',
            name='biological_replicate_protocols',
            field=models.ManyToManyField(blank=True, to='db.BiologicalReplicateProtocol'),
        ),
    ]
