version: "3.9"
   
services:
  db:
    container_name: db
    image: postgres:latest
    restart: always
    volumes:
      - ./docker/persistence/postgresql/:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - djangonetwork
  django:
    build: 
      context: .
      dockerfile: docker/Dockerfile.django
    environment:
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: ./docker/django_entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork
  redis:
    expose:
      - "6379"
    image: redis:latest
    restart: always
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge
