# syntax=docker/dockerfile:1
FROM ubuntu:jammy
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
WORKDIR /code
#COPY required config files first

####SYSTEM UPDATES####
RUN apt-get update \
  && DEBIAN_FRONTEND="noninteractive" apt-get install -y --no-install-recommends build-essential \ 
  libpq-dev tzdata gcc-multilib g++-multilib ca-certificates curl graphviz \  
  && rm -rf /var/lib/apt/lists/*
####INSTALL MINICONDA AND QIIME2####
RUN curl -LO "http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh" \
    && bash Miniconda3-latest-Linux-x86_64.sh -p /miniconda -b
ENV PATH=/miniconda/bin:${PATH}
RUN conda update -y conda \
    && conda create --name quorem python=3.8.12
RUN conda init bash
#This is the way to run a conda command when you can't activate, which we can't
#seem to from in here at build time, so this activates RUN commands that follow
# see: https://pythonspeed.com/articles/activate-conda-dockerfile/
SHELL ["conda", "run", "-n", "quorem", "/bin/bash", "-c"]
COPY ../scripts/qiime2/qiime2-2022.8-py38-linux-conda.yml /code/
RUN conda env update --file qiime2-2022.8-py38-linux-conda.yml
#Activate bash with conda for future interactive sessions
COPY ../requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt
#Using VOLUME here causes timeouts with http on Django image for some reason
COPY .. /code/
